Gulitdu/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
import xadmin
from django.conf import settings
from django.views.static import serve
from users.views import index

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('xadmin/', xadmin.site.urls),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('courses/', include(('courses.urls', 'courses'), namespace='courses')),
    path('orgs/', include(('orgs.urls', 'orgs'), namespace='orgs')),
    path('operations/', include(('operations.urls', 'operations'), namespace='operations')),
    path('', index, name='index')
]

apps/users/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import user_register

urlpatterns = [
    path('user_register/', user_register, name='user_register')
]

apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import datetime


# Create your models here.
class UserProfile(AbstractUser):
    image = models.ImageField(upload_to='user/', max_length=200, verbose_name='用户头像', null=True, blank=True)
    nick_name = models.CharField(max_length=20, verbose_name='用户昵称', null=True, blank=True)
    birthday = models.DateTimeField(verbose_name='用户生日', null=True, blank=True)
    gender = models.CharField(choices=(('girl', '女'), ('boy', '男')), max_length=10, verbose_name='用户性别', default='girl')
    address = models.CharField(max_length=200, verbose_name='用户地址', null=True, blank=True)
    phone = models.CharField(max_length=11, verbose_name='用户手机', null=True, blank=True)
    email = models.CharField(max_length=50, verbose_name='用户邮箱', null=True, blank=True)
    create_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = '用户信息'
        verbose_name_plural = verbose_name


class BannerInfo(models.Model):
    image = models.ImageField(upload_to='banner/', verbose_name='轮播图', max_length=200)
    url = models.URLField(default='http://www.baidu.com', max_length=200, verbose_name='图片链接')
    title = models.CharField(max_length=200, verbose_name='图片标题', null=True, blank=True)
    create_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return str(self.image)

    class Meta:
        verbose_name = '轮播图'
        verbose_name_plural = verbose_name


class EmailVerifyDode(models.Model):
    code = models.CharField(max_length=200, verbose_name='邮箱验证码')
    email = models.EmailField(max_length=50, verbose_name='验证码邮箱')
    send_type = models.IntegerField(choices=((1, 'register'), (2, 'forget'), (3, 'change')),verbose_name='验证码类型')
    create_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')


    def __str__(self):
        return self.code

    class Meta:
        verbose_name = '验证码邮箱信息'
        verbose_name_plural = verbose_name

apps/users/forms.py
from django import forms


class UserRegisterForm(forms.Form):
    email = forms.EmailField(required=True)
    password = forms.CharField(required=True, min_length=3, max_length=15, error_messages={
        'required': '密码必须填写',
        'min_length': '密码不能少于3位',
        'max_length': '密码不能超过15位',
    })

apps/users/views.py
from django.shortcuts import render, redirect, reverse
from .forms import UserRegisterForm
from .models import UserProfile
from django.db.models import Q


# Create your views here.
def index(request):
    return render(request, 'index.html')


def user_register(request):
    if request.method == 'GET':
        return render(request, 'users/register.html')
    else:
        user_register_form = UserRegisterForm(request.POST)
        if user_register_form.is_valid():
            email = user_register_form.changed_data['email']
            password = user_register_form.changed_data['password']

            user_list = UserProfile.objects.filter(Q(username=email) | Q(email=email))
            if user_list:
                return render(request, 'users/register.html', {'msg': '用户已存在'})
            else:
                user = UserProfile
                user.username = email
                user.set_password(password)
                user.email = email
                user.save()
                return redirect(reverse('index'))
        else:
            return render(request, 'users/register.html', {'user_register_form': user_register_form})

templates/users/register.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
    <title>谷粒教育注册</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">

</head>
<body>

<header>
    <div class="c-box fff-box">
        <div class="wp header-box">
            <p class="fl hd-tips">谷粒教育，在线学习平台！</p>
            <ul class="fr hd-bar">
                <li>服务电话：<span>88888888</span></li>
                <li><a href="login.html">[登录]</a></li>
                <li class="active"><a href="{% url 'users:user_register' %}">[注册]</a></li>
            </ul>
        </div>
    </div>
</header>
<section>
    <div class="c-box bg-box">
        <div class="login-box clearfix">
            <div class="hd-login clearfix">
                <a class="index-logo" href="{% url 'index' %}"></a>
                <h1>用户注册</h1>
                <a class="index-font" href="{% url 'index' %}">回到首页</a>
            </div>
            <div class="fl slide">
                <div class="imgslide">
                    <ul class="imgs">

                        <li><a href=""><img width="483" height="472" src="{% static 'images/mysql.jpg' %}" /></a></li>

                        <li><a href=""><img width="483" height="472" src="{% static 'images/mongoDB.jpg' %}" /></a></li>

                        <li><a href=""><img width="483" height="472" src="{% static 'images/mysql.jpg' %}" /></a></li>

                    </ul>
                </div>
                <div class="unslider-arrow prev"></div>
                <div class="unslider-arrow next"></div>
            </div>
            <div class="fl form-box">
                <div class="tab">
                    <h2>邮箱注册</h2>
                </div>
                
                <div class="tab-form">
                    <form id="email_register_form" method="post" action="{% url 'users:user_register' %}" autocomplete="off">
                        {% csrf_token %}
                        <div class="form-group marb20 ">
                            <label>邮&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;箱</label>
                            <input  type="text" id="id_email" name="email" value="None" placeholder="请输入您的邮箱地址" />
                        </div>
                        <div class="form-group marb8 ">
                            <label>密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</label>
                            <input type="password" id="id_password" name="password"  value="None" placeholder="请输入6-20位非中文字符密码" />
                        </div>
                        <div class="form-group marb8 captcha1 ">
                            <label>验&nbsp;证&nbsp;码</label>
                            <img src="/captcha/image/2f3f82e5f7a054bf5caa93b9b0bb6cc308fb7011/" alt="captcha" class="captcha" /> <input id="id_captcha_0" name="captcha_0" type="hidden" value="2f3f82e5f7a054bf5caa93b9b0bb6cc308fb7011" /> <input autocomplete="off" id="id_captcha_1" name="captcha_1" type="text" />
                        </div>
                        <div class="error btns" id="jsEmailTips">
                            {{ msg }}
                            {% for key,err in user_register_form.errors.items %}
                                {{ err }}
                            {% endfor %}
                        </div>
                        <div class="auto-box marb8">
                        </div>
                        <input class="btn btn-green" id="jsEmailRegBtn" type="submit" value="注册并登录" />
                    </form>
                </div>
                <p class="form-p">已有账号？<a href="login.html">[立即登录]</a></p>
            </div>
        </div>
    </div>
</section>

<input id="isLogin" type="hidden" value="False"/>
<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/validateDialog.js' %}"  type="text/javascript"></script>
<script src="{% static 'js/login.js' %}"  type="text/javascript"></script>
</body>
</html>